### ISSUE TITLE
Project name when creating Manage.yml

### ISSUE THREAD

**Issue by vmesel** [rochacbruno-archive/manage#2]
- Manage version: 0.1.7
- Python version: 3.4.1
- Operating System: MacOSX El Capitan
### Description

The manage project is very useful, but we cannot set a project name when creating the manage.yml file with the **manage init** it would be nice to have such thing.
### What can be done

Add an option in the manage init command like "--project-name" and let the user enter his project name as should be.

**Comment by rochacbruno** [comment]
This can be added in this line https://github.com/rochacbruno/manage/blob/master/manage/cli.py#L84

before writing the file, change the default_manage_dict['project_name']

**Comment by vmesel** [comment]
Gonna do dat, just let me get some things from FastaDB ready and it will be done ASAP!
